const logs = [
    {
        id: "1",
        date: "December 28, 2023",
        employee_id: "00001",
        employee_name: "John Doe",
        time_in: "8:00 am",
        time_in_location: "Manila Philippines",
        time_in_Image: "",
        time_out: "5:00 pm",
        time_out_location: "Manila Philippines",
        time_out_image: "",
        st: "",
        ot: "",
        late: "",
        ut: "",
    },
    {
        id: "2",
        date: "December 28, 2023",
        employee_id: "00002",
        employee_name: "Jane Doe",
        time_in: "8:00 am",
        time_in_location: "Manila Philippines",
        time_in_Image: "",
        time_out: "5:00 pm",
        time_out_location: "Manila Philippines",
        time_out_image: "",
        st: "",
        ot: "",
        late: "",
        ut: "",
    },
    {
        id: "3",
        date: "December 28, 2023",
        employee_id: "00003",
        employee_name: "Joe Doe",
        time_in: "8:00 am",
        time_in_location: "Manila Philippines",
        time_in_Image: "",
        time_out: "5:00 pm",
        time_out_location: "Manila Philippines",
        time_out_image: "",
        st: "",
        ot: "",
        late: "",
        ut: "",
    },
    {
        id: "4",
        date: "December 28, 2023",
        employee_id: "00004",
        employee_name: "Joel Doe",
        time_in: "8:00 am",
        time_in_location: "Manila Philippines",
        time_in_Image: "",
        time_out: "5:00 pm",
        time_out_location: "Manila Philippines",
        time_out_image: "",
        st: "",
        ot: "",
        late: "",
        ut: "",
    },
]

export default logs